### ISSUE TITLE
 Forum LogIn

### ISSUE THREAD

**Issue by butler-hw** [Heydenwall/error-reports#22]
Reporter: Rabanus

Aloha,
ich kann mich auch mit den hinterlegten Daten nicht mehr im Forum anmelden. Habe zusätzlich diverse Kombis ausprobiert, aber auch kein Zufallstreffer. Und ja, ich bin mir bewusst, dass der Fehler meistens vor dem Monitor sitzt.
LG
Rabanus

**Comment by tled** [comment]
Der Benutzername vom Account wurde geändert. Auf der Cloud musste dieser entfernt und neu angelegt werden. Testlauf war erfolgreich.
